<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="Run on Firefox"
           tests="7"
           failures="1"
           errors="0"
           skipped="0"
           time="6.305">
  <properties />
            <testcase name="TC_02_Sort_Name_Z_To_A" time="0.948" classname="com.nopcommerce.user.Sort_User_Nopcommerce">
                <failure type="java.lang.AssertionError"
                  message="expected [true] but found [false]"
              >
<![CDATA[java.lang.AssertionError: expected [true] but found [false]
  org.testng.Assert.fail(Assert.java:96)
  org.testng.Assert.failNotEquals(Assert.java:776)
  org.testng.Assert.assertTrue(Assert.java:44)
  org.testng.Assert.assertTrue(Assert.java:54)
  commons.BaseTest.checkTrue(BaseTest.java:76)
  commons.BaseTest.verifyTrue(BaseTest.java:88)
  com.nopcommerce.user.Sort_User_Nopcommerce.TC_02_Sort_Name_Z_To_A(Sort_User_Nopcommerce.java:56)
  java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  java.base/java.lang.reflect.Method.invoke(Method.java:566)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
  org.testng.TestRunner.privateRun(TestRunner.java:648)
  org.testng.TestRunner.run(TestRunner.java:505)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
  org.testng.SuiteRunner.run(SuiteRunner.java:364)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
  org.testng.TestNG.runSuites(TestNG.java:1049)
  org.testng.TestNG.run(TestNG.java:1017)
  org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
  org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
  org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
      </failure>

          </testcase>
  
  
            <testcase name="TC_05_Displaye_03_Product" time="0.001" classname="com.nopcommerce.user.Sort_User_Nopcommerce" />
                <testcase name="TC_06_Displaye_06_Product" time="0.002" classname="com.nopcommerce.user.Sort_User_Nopcommerce" />
                <testcase name="TC_03_Sort_Price_Low_To_High" time="0.956" classname="com.nopcommerce.user.Sort_User_Nopcommerce" />
                <testcase name="TC_07_Displaye_09_Product" time="0.001" classname="com.nopcommerce.user.Sort_User_Nopcommerce" />
                <testcase name="TC_01_Sort_Name_A_To_Z" time="3.457" classname="com.nopcommerce.user.Sort_User_Nopcommerce" />
                <testcase name="TC_04_Sort_Price_High_To_Low" time="0.940" classname="com.nopcommerce.user.Sort_User_Nopcommerce" />
      
</testsuite>
